apiVersion: gcp.platformref.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: bertelli10-cl
  labels:
    backstage.io/kubernetes-id: bertelli10
spec:
  compositionSelector:
    matchLabels:
      provider: GCP
  id: bertelli10-cl
  parameters:
    nodes:
      count: 1
      size: small
    services:
      operators:
        prometheus:
          version: "10.0.2"
    networkRef:
      id: bertelli10-nw
  writeConnectionSecretToRef:
    name: cluster-conn
