apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: bertelli10-sql
  labels:
    backstage.io/kubernetes-id: bertelli10
spec:
  forProvider:
    databaseVersion: POSTGRES_9_6
    region: europe-west3
    settings:
      tier: db-custom-1-3840
      dataDiskType: PD_SSD
      dataDiskSizeGb: 10
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: cloudsqlpostgresql-conn
